style"arrow"{
engine"pixmap"{
image{
function=ARROW
state=INSENSITIVE
file="images/arrow-bg.svg"
stretch=FALSE
overlay_file="images/colorspecific/arrow-up_insensitive.svg"
overlay_stretch=FALSE
arrow_direction=UP}
image{
function=ARROW
state=INSENSITIVE
file="images/arrow-bg.svg"
stretch=FALSE
overlay_file="images/colorspecific/arrow-down_insensitive.svg"
overlay_stretch=FALSE
arrow_direction=DOWN}
image{
function=ARROW
state=INSENSITIVE
file="images/arrow-bg.svg"
stretch=FALSE
overlay_file="images/colorspecific/arrow-left_insensitive.svg"
overlay_stretch=FALSE
arrow_direction=LEFT}
image{
function=ARROW
state=INSENSITIVE
file="images/arrow-bg.svg"
stretch=FALSE
overlay_file="images/colorspecific/arrow-right_insensitive.svg"
overlay_stretch=FALSE
arrow_direction=RIGHT}
image{
function=ARROW
state=NORMAL
file="images/arrow-bg.svg"
stretch=FALSE
overlay_file="images/colorspecific/arrow-up_normal.svg"
overlay_stretch=FALSE
arrow_direction=UP}
image{
function=ARROW
state=NORMAL
file="images/arrow-bg.svg"
stretch=FALSE
overlay_file="images/colorspecific/arrow-down_normal.svg"
overlay_stretch=FALSE
arrow_direction=DOWN}
image{
function=ARROW
state=NORMAL
file="images/arrow-bg.svg"
stretch=FALSE
overlay_file="images/colorspecific/arrow-left_normal.svg"
overlay_stretch=FALSE
arrow_direction=LEFT}
image{
function=ARROW
state=NORMAL
file="images/arrow-bg.svg"
stretch=FALSE
overlay_file="images/colorspecific/arrow-right_normal.svg"
overlay_stretch=FALSE
arrow_direction=RIGHT}
image{
function=ARROW
state=ACTIVE
file="images/arrow-bg.svg"
stretch=FALSE
overlay_file="images/colorspecific/arrow-up_normal.svg"
overlay_stretch=FALSE
arrow_direction=UP}
image{
function=ARROW
state=ACTIVE
file="images/arrow-bg.svg"
stretch=FALSE
overlay_file="images/colorspecific/arrow-down_normal.svg"
overlay_stretch=FALSE
arrow_direction=DOWN}
image{
function=ARROW
state=ACTIVE
file="images/arrow-bg.svg"
stretch=FALSE
overlay_file="images/colorspecific/arrow-left_normal.svg"
overlay_stretch=FALSE
arrow_direction=LEFT}
image{
function=ARROW
state=ACTIVE
file="images/arrow-bg.svg"
stretch=FALSE
overlay_file="images/colorspecific/arrow-right_normal.svg"
overlay_stretch=FALSE
arrow_direction=RIGHT}
image{
function=ARROW
state=PRELIGHT
file="images/arrow-bg.svg"
stretch=FALSE
overlay_file="images/colorspecific/arrow-up_normal.svg"
overlay_stretch=FALSE
arrow_direction=UP}
image{
function=ARROW
state=PRELIGHT
file="images/arrow-bg.svg"
stretch=FALSE
overlay_file="images/colorspecific/arrow-down_normal.svg"
overlay_stretch=FALSE
arrow_direction=DOWN}
image{
function=ARROW
state=PRELIGHT
file="images/arrow-bg.svg"
stretch=FALSE
overlay_file="images/colorspecific/arrow-left_normal.svg"
overlay_stretch=FALSE
arrow_direction=LEFT}
image{
function=ARROW
state=PRELIGHT
file="images/arrow-bg.svg"
stretch=FALSE
overlay_file="images/colorspecific/arrow-right_normal.svg"
overlay_stretch=FALSE
arrow_direction=RIGHT}}}
class "*GtkArrow"style"arrow"
