style"checkbutton"{
engine"pixmap"{
image{
function=CHECK
state=INSENSITIVE
shadow=OUT
file="images/check.svg"
stretch=TRUE
border={7,7,7,7}}
image{
function=CHECK
state=NORMAL
shadow=OUT
file="images/check.svg"
stretch=TRUE
border={7,7,7,7}}
image{
function=CHECK
state=PRELIGHT
shadow=OUT
file="images/check.svg"
stretch=TRUE
border={7,7,7,7}}
image{
function=CHECK
state=ACTIVE
shadow=OUT
file="images/check.svg"
stretch=TRUE
border={7,7,7,7}}
image{
function=CHECK
state=INSENSITIVE
shadow=ETCHED_IN
file="images/colorspecific/check_semi.svg"
stretch=TRUE
border={7,7,7,7}}
image{
function=CHECK
state=NORMAL
shadow=ETCHED_IN
file="images/colorspecific/check_semi.svg"
stretch=TRUE
border={7,7,7,7}}
image{
function=CHECK
state=PRELIGHT
shadow=ETCHED_IN
file="images/colorspecific/check_semi.svg"
stretch=TRUE
border={7,7,7,7}}
image{
function=CHECK
state=ACTIVE
shadow=ETCHED_IN
file="images/colorspecific/check_semi.svg"
stretch=TRUE
border={7,7,7,7}}
image{
function=CHECK
state=INSENSITIVE
shadow=ETCHED_OUT
file="images/colorspecific/check_semi.svg"
stretch=TRUE
border={7,7,7,7}}
image{
function=CHECK
state=NORMAL
shadow=ETCHED_OUT
file="images/colorspecific/check_semi.svg"
stretch=TRUE
border={7,7,7,7}}
image{
function=CHECK
state=PRELIGHT
shadow=ETCHED_OUT
file="images/colorspecific/check_semi.svg"
stretch=TRUE
border={7,7,7,7}}
image{
function=CHECK
state=ACTIVE
shadow=ETCHED_OUT
file="images/colorspecific/check_semi.svg"
stretch=TRUE
border={7,7,7,7}}
image{
function=CHECK
state=INSENSITIVE
shadow=IN
file="images/colorspecific/check_checked.svg"
stretch=TRUE
border={7,7,7,7}}
image{
function=CHECK
state=NORMAL
shadow=IN
file="images/colorspecific/check_checked.svg"
stretch=TRUE
border={7,7,7,7}}
image{
function=CHECK
state=PRELIGHT
shadow=IN
file="images/colorspecific/check_checked.svg"
stretch=TRUE
border={7,7,7,7}}
image{
function=CHECK
state=ACTIVE
shadow=IN
file="images/colorspecific/check_checked.svg"
stretch=TRUE
border={7,7,7,7}}}}
class "*GtkCheckButton"style"checkbutton"
