style"expander"{
GtkExpander::expander-size=12
GtkExpander::expander-spacing=5
engine"pixmap"{
image{
function=TAB
state=INSENSITIVE
detail="optionmenutab"
file="images/arrow-bg.svg"
stretch=FALSE
overlay_file="images/colorspecific/arrow-down_insensitive.svg"
overlay_stretch=FALSE}
image{
function=TAB
state=NORMAL
detail="optionmenutab"
file="images/arrow-bg.svg"
stretch=FALSE
overlay_file="images/colorspecific/arrow-down_normal.svg"
overlay_stretch=FALSE}
image{
function=TAB
state=PRELIGHT
detail="optionmenutab"
file="images/arrow-bg.svg"
stretch=FALSE
overlay_file="images/colorspecific/arrow-down_normal.svg"
overlay_stretch=FALSE}
image{
function=TAB
state=ACTIVE
detail="optionmenutab"
file="images/arrow-bg.svg"
stretch=FALSE
overlay_file="images/colorspecific/arrow-down_normal.svg"
overlay_stretch=FALSE}}}
class "*GtkExpander"style"expander"
