style"frame"{
xthickness=1
ythickness=2
engine"pixmap"{
image{
function=SHADOW_GAP
shadow=IN
file="images/frame-in-gap.svg"
border={3,3,3,3}
stretch=TRUE
gap_start_file="images/frame-in-gap-start.svg"
gap_start_border={3,0,2,0}
gap_end_file="images/frame-in-gap-end.svg"
gap_end_border={0,3,0,2}
gap_file="images/none.svg"}
image{
function=SHADOW_GAP
shadow=ETCHED_IN
file="images/frame-in-gap.svg"
border={2,2,3,2}
stretch=TRUE
gap_start_file="images/frame-in-gap-start.svg"
gap_start_border={3,0,2,0}
gap_end_file="images/frame-in-gap-end.svg"
gap_end_border={0,3,0,2}
gap_file="images/none.svg"}
image{
function=SHADOW_GAP
shadow=OUT
file="images/frame-out-gap.svg"
border={3,3,3,3}
stretch=TRUE
gap_start_file="images/frame-out-gap-start.svg"
gap_start_border={3,0,2,0}
gap_end_file="images/frame-out-gap-end.svg"
gap_end_border={0,3,0,2}
gap_file="images/none.svg"}
image{
function=SHADOW_GAP
shadow=ETCHED_OUT
file="images/frame-out-gap.svg"
border={2,2,3,2}
stretch=TRUE
gap_start_file="images/frame-out-gap-start.svg"
gap_start_border={3,0,2,0}
gap_end_file="images/frame-out-gap-end.svg"
gap_end_border={0,3,0,2}
gap_file="images/none.svg"}
image{
function=SHADOW
shadow=IN
file="images/frame-in.svg"
border={5,5,5,5}
stretch=TRUE}
image{
function=SHADOW
shadow=ETCHED_IN
file="images/frame-in.svg"
border={5,5,5,5}
stretch=TRUE}
image{
function=SHADOW
shadow=OUT
file="images/frame-out.svg"
border={5,5,5,5}
stretch=TRUE}
image{
function=SHADOW
shadow=ETCHED_OUT
file="images/frame-out.svg"
border={5,5,5,5}
stretch=TRUE}}}
class"GtkFrame"style"frame"
