style"menubar"{
xthickness=0
ythickness=0
GtkMenuBar::shadow-type=GTK_SHADOW_IN
GtkMenuBar::internal-padding=3
GtkMenuBar::space-size=0
engine"pixmap"{
image{
function=SHADOW
shadow=IN
file="images/toolbar-shadow.svg"
border={0,0,1,1}
stretch=TRUE}}}
class"GtkMenuBar"style"menubar"

style"menubaritem"{
xthickness=0
ythickness=2
GtkMenuItem::selected-shadow-type=GTK_SHADOW_NONE
GtkMenuItem::horizontal-padding=10
fg[PRELIGHT]=@selected_fg_color
engine"pixmap"{
image{
function=BOX
state=PRELIGHT
file="images/colorspecific/menubaritem.svg"
border={5,5,5,5}
stretch=TRUE}}}
widget_class"*<GtkMenuBar>.<GtkMenuItem>*"style"menubaritem"

style"menubartoolbar"{
GtkMenuBar::shadow-type=GTK_SHADOW_NONE}
widget"*GtkToolbar*GtkMenuBar"style"menubartoolbar"
