style"notebook"{
xthickness=1
ythickness=1
GtkNotebook::tab-curvature=40
GtkNotebook::tab-overlap=1
engine"pixmap"{
image{
function=SHADOW
file="images/none.svg"
stretch=FALSE}
image{
function=BOX_GAP
file="images/notebook-shadow.svg"
detail="notebook"
border={1,1,1,1}
stretch=TRUE
gap_file="images/tab-line.svg"
gap_border={0,0,0,0}}
image{
function=EXTENSION
state=ACTIVE
file="images/colorspecific/base-bg.svg"
stretch=TRUE
overlay_file="images/tab-top_normal.svg"
overlay_border={2,2,13,13}
overlay_stretch=TRUE
gap_side=BOTTOM}
image{
function=EXTENSION
file="images/colorspecific/base-bg.svg"
stretch=TRUE
overlay_file="images/colorspecific/tab-top_active.svg"
overlay_border={5,5,2,2}
overlay_stretch=TRUE
gap_side=BOTTOM}
image{
function=EXTENSION
state=ACTIVE
file="images/colorspecific/base-bg.svg"
stretch=TRUE
overlay_file="images/tab-bottom_normal.svg"
overlay_border={2,2,2,2}
overlay_stretch=TRUE
gap_side=TOP}
image{
function=EXTENSION
file="images/colorspecific/base-bg.svg"
stretch=TRUE
overlay_file="images/colorspecific/tab-bottom_active.svg"
overlay_border={5,5,2,2}
overlay_stretch=TRUE
gap_side=TOP}
image{
function=EXTENSION
state=ACTIVE
file="images/colorspecific/base-bg.svg"
stretch=TRUE
overlay_file="images/tab-right_normal.svg"
overlay_border={2,2,2,2}
overlay_stretch=TRUE
gap_side=LEFT}
image{
function=EXTENSION
file="images/colorspecific/base-bg.svg"
stretch=TRUE
overlay_file="images/colorspecific/tab-right_active.svg"
overlay_border={2,2,5,5}
overlay_stretch=TRUE
gap_side=LEFT}
image{
function=EXTENSION
state=ACTIVE
file="images/colorspecific/base-bg.svg"
stretch=TRUE
overlay_file="images/tab-left_normal.svg"
overlay_border={2,2,2,2}
overlay_stretch=TRUE
gap_side=RIGHT}
image{
function=EXTENSION
file="images/colorspecific/base-bg.svg"
stretch=TRUE
overlay_file="images/colorspecific/tab-left_active.svg"
overlay_border={2,2,5,5}
overlay_stretch=TRUE
gap_side=RIGHT}
image{
function=ARROW
state=INSENSITIVE
file="images/arrow-bg.svg"
stretch=FALSE
overlay_file="images/colorspecific/arrow-up_insensitive.svg"
overlay_stretch=FALSE
arrow_direction=UP}
image{
function=ARROW
state=INSENSITIVE
file="images/arrow-bg.svg"
stretch=FALSE
overlay_file="images/colorspecific/arrow-down_insensitive.svg"
overlay_stretch=FALSE
arrow_direction=DOWN}
image{
function=ARROW
state=INSENSITIVE
file="images/arrow-bg.svg"
stretch=FALSE
overlay_file="images/colorspecific/arrow-left_insensitive.svg"
overlay_stretch=FALSE
arrow_direction=LEFT}
image{
function=ARROW
state=INSENSITIVE
file="images/arrow-bg.svg"
stretch=FALSE
overlay_file="images/colorspecific/arrow-right_insensitive.svg"
overlay_stretch=FALSE
arrow_direction=RIGHT}
image{
function=ARROW
state=NORMAL
file="images/arrow-bg.svg"
stretch=FALSE
overlay_file="images/colorspecific/arrow-up_normal.svg"
overlay_stretch=FALSE
arrow_direction=UP}
image{
function=ARROW
state=NORMAL
file="images/arrow-bg.svg"
stretch=FALSE
overlay_file="images/colorspecific/arrow-down_normal.svg"
overlay_stretch=FALSE
arrow_direction=DOWN}
image{
function=ARROW
state=NORMAL
file="images/arrow-bg.svg"
stretch=FALSE
overlay_file="images/colorspecific/arrow-left_normal.svg"
overlay_stretch=FALSE
arrow_direction=LEFT}
image{
function=ARROW
state=NORMAL
file="images/arrow-bg.svg"
stretch=FALSE
overlay_file="images/colorspecific/arrow-right_normal.svg"
overlay_stretch=FALSE
arrow_direction=RIGHT}
image{
function=ARROW
state=ACTIVE
file="images/arrow-bg.svg"
stretch=FALSE
overlay_file="images/colorspecific/arrow-up_normal.svg"
overlay_stretch=FALSE
arrow_direction=UP}
image{
function=ARROW
state=ACTIVE
file="images/arrow-bg.svg"
stretch=FALSE
overlay_file="images/colorspecific/arrow-down_normal.svg"
overlay_stretch=FALSE
arrow_direction=DOWN}
image{
function=ARROW
state=ACTIVE
file="images/arrow-bg.svg"
stretch=FALSE
overlay_file="images/colorspecific/arrow-left_normal.svg"
overlay_stretch=FALSE
arrow_direction=LEFT}
image{
function=ARROW
state=ACTIVE
file="images/arrow-bg.svg"
stretch=FALSE
overlay_file="images/colorspecific/arrow-right_normal.svg"
overlay_stretch=FALSE
arrow_direction=RIGHT}
image{
function=ARROW
state=PRELIGHT
file="images/arrow-bg.svg"
stretch=FALSE
overlay_file="images/colorspecific/arrow-up_normal.svg"
overlay_stretch=FALSE
arrow_direction=UP}
image{
function=ARROW
state=PRELIGHT
file="images/arrow-bg.svg"
stretch=FALSE
overlay_file="images/colorspecific/arrow-down_normal.svg"
overlay_stretch=FALSE
arrow_direction=DOWN}
image{
function=ARROW
state=PRELIGHT
file="images/arrow-bg.svg"
stretch=FALSE
overlay_file="images/colorspecific/arrow-left_normal.svg"
overlay_stretch=FALSE
arrow_direction=LEFT}
image{
function=ARROW
state=PRELIGHT
file="images/arrow-bg.svg"
stretch=FALSE
overlay_file="images/colorspecific/arrow-right_normal.svg"
overlay_stretch=FALSE
arrow_direction=RIGHT}
}}class"GtkNotebook"style"notebook"

style"notebooklabel"{
fg[ACTIVE]=@inactive_fg_color
engine"mist"{
}}widget"*GtkNotebook.GtkLabel"style"notebooklabel"

style"notebooksteppers"{
GtkNotebook::has-backward-stepper=1
GtkNotebook::has-forward-stepper=1
GtkNotebook::has-secondary-backward-stepper=0
GtkNotebook::has-secondary-forward-stepper=0
}class"*"style"notebooksteppers"
