style"optionmenu" = "button"{
GtkOptionMenu::indicator-spacing={5,10,5,5}
engine"pixmap"{
image{
function=BOX
shadow=OUT
overlay_file="images/button-normal.svg"
overlay_border={5,5,5,5}
overlay_stretch=TRUE}
image{
function=BOX
shadow=IN
overlay_file="images/button-pressed.svg"
overlay_border={5,5,5,5}
overlay_stretch=TRUE}
image{
function=FOCUS
file="images/none.svg"
stretch=FALSE}
image{
function=TAB
state=INSENSITIVE
detail="optionmenutab"
file="images/arrow-bg.svg"
stretch=FALSE
overlay_file="images/colorspecific/arrow-down_insensitive.svg"
overlay_stretch=FALSE}
image{
function=TAB
state=NORMAL
detail="optionmenutab"
file="images/arrow-bg.svg"
stretch=FALSE
overlay_file="images/colorspecific/arrow-down_normal.svg"
overlay_stretch=FALSE}
image{
function=TAB
state=PRELIGHT
detail="optionmenutab"
file="images/arrow-bg.svg"
stretch=FALSE
overlay_file="images/colorspecific/arrow-down_normal.svg"
overlay_stretch=FALSE}
image{
function=TAB
state=ACTIVE
detail="optionmenutab"
file="images/arrow-bg.svg"
stretch=FALSE
overlay_file="images/colorspecific/arrow-down_normal.svg"
overlay_stretch=FALSE}}}
class "*GtkOptionMenu"style"optionmenu"
