style"radiobutton"{
engine"pixmap"{
image{
function=OPTION
state=INSENSITIVE
shadow=OUT
file="images/radio.svg"
stretch=TRUE
border={7,7,7,7}}
image{
function=OPTION
state=NORMAL
shadow=OUT
file="images/radio.svg"
stretch=TRUE
border={7,7,7,7}}
image{
function=OPTION
state=PRELIGHT
shadow=OUT
file="images/radio.svg"
stretch=TRUE
border={7,7,7,7}}
image{
function=OPTION
state=ACTIVE
shadow=OUT
file="images/radio.svg"
stretch=TRUE
border={7,7,7,7}}
image{
function=OPTION
state=INSENSITIVE
shadow=ETCHED_IN
file="images/colorspecific/radio_semi.svg"
stretch=TRUE
border={7,7,7,7}}
image{
function=OPTION
state=NORMAL
shadow=ETCHED_IN
file="images/colorspecific/radio_semi.svg"
stretch=TRUE
border={7,7,7,7}}
image{
function=OPTION
state=PRELIGHT
shadow=ETCHED_IN
file="images/colorspecific/radio_semi.svg"
stretch=TRUE
border={7,7,7,7}}
image{
function=OPTION
state=ACTIVE
shadow=ETCHED_IN
file="images/colorspecific/radio_semi.svg"
stretch=TRUE
border={7,7,7,7}}
image{
function=OPTION
state=INSENSITIVE
shadow=ETCHED_OUT
file="images/colorspecific/radio_semi.svg"
stretch=TRUE
border={7,7,7,7}}
image{
function=OPTION
state=NORMAL
shadow=ETCHED_OUT
file="images/colorspecific/radio_semi.svg"
stretch=TRUE
border={7,7,7,7}}
image{
function=OPTION
state=PRELIGHT
shadow=ETCHED_OUT
file="images/colorspecific/radio_semi.svg"
stretch=TRUE
border={7,7,7,7}}
image{
function=OPTION
state=ACTIVE
shadow=ETCHED_OUT
file="images/colorspecific/radio_semi.svg"
stretch=TRUE
border={7,7,7,7}}
image{
function=OPTION
state=INSENSITIVE
shadow=IN
file="images/colorspecific/radio_checked.svg"
stretch=TRUE
border={7,7,7,7}}
image{
function=OPTION
state=NORMAL
shadow=IN
file="images/colorspecific/radio_checked.svg"
stretch=TRUE
border={7,7,7,7}}
image{
function=OPTION
state=PRELIGHT
shadow=IN
file="images/colorspecific/radio_checked.svg"
stretch=TRUE
border={7,7,7,7}}
image{
function=OPTION
state=ACTIVE
shadow=IN
file="images/colorspecific/radio_checked.svg"
stretch=TRUE
border={7,7,7,7}}}}
class "*GtkRadioButton"style"radiobutton"
