style "scrollbar"{
bg[NORMAL]=shade(0.95,@base_color)
bg[PRELIGHT]=shade(0.95,@base_color)
bg[SELECTED]=shade(0.95,@base_color)
bg[ACTIVE]=shade(0.95,@base_color)
bg[INSENSITIVE]=shade(0.95,@base_color)
xthickness=0
ythickness=0
GtkScrollbar::min-slider-length=40
GtkScrollbar::fixed-slider-length=1
GtkRange::activate-slider=0
GtkRange::slider-width=14
GtkRange::stepper-size=14
GtkRange::stepper-spacing=0
GtkRange::trough-border=1
GtkRange::trough-under-steppers=1
engine"pixmap"{
image{
function=BOX
detail="trough"
file="images/colorspecific/base-bg.svg"
stretch=TRUE
overlay_file="images/scrollbar.svg"
overlay_border={1,1,1,1}
overlay_stretch=TRUE}
image{
function=SLIDER
orientation=VERTICAL
overlay_file="images/colorspecific/scrollbar-slider.svg"
overlay_stretch=TRUE
overlay_border={5,5,5,5}}
image{
function=SLIDER
orientation=HORIZONTAL
overlay_file="images/colorspecific/scrollbar-slider.svg"
overlay_stretch=TRUE
overlay_border={5,5,5,5}}
image{
function=ARROW
state=INSENSITIVE
file="images/arrow-bg.svg"
stretch=FALSE
overlay_file="images/colorspecific/arrow-up_insensitive.svg"
overlay_stretch=FALSE
arrow_direction=UP}
image{
function=ARROW
state=INSENSITIVE
file="images/arrow-bg.svg"
stretch=FALSE
overlay_file="images/colorspecific/arrow-down_insensitive.svg"
overlay_stretch=FALSE
arrow_direction=DOWN}
image{
function=ARROW
state=INSENSITIVE
file="images/arrow-bg.svg"
stretch=FALSE
overlay_file="images/colorspecific/arrow-left_insensitive.svg"
overlay_stretch=FALSE
arrow_direction=LEFT}
image{
function=ARROW
state=INSENSITIVE
file="images/arrow-bg.svg"
stretch=FALSE
overlay_file="images/colorspecific/arrow-right_insensitive.svg"
overlay_stretch=FALSE
arrow_direction=RIGHT}
image{
function=ARROW
state=NORMAL
file="images/arrow-bg.svg"
stretch=FALSE
overlay_file="images/colorspecific/arrow-up_normal.svg"
overlay_stretch=FALSE
arrow_direction=UP}
image{
function=ARROW
state=NORMAL
file="images/arrow-bg.svg"
stretch=FALSE
overlay_file="images/colorspecific/arrow-down_normal.svg"
overlay_stretch=FALSE
arrow_direction=DOWN}
image{
function=ARROW
state=NORMAL
file="images/arrow-bg.svg"
stretch=FALSE
overlay_file="images/colorspecific/arrow-left_normal.svg"
overlay_stretch=FALSE
arrow_direction=LEFT}
image{
function=ARROW
state=NORMAL
file="images/arrow-bg.svg"
stretch=FALSE
overlay_file="images/colorspecific/arrow-right_normal.svg"
overlay_stretch=FALSE
arrow_direction=RIGHT}
image{
function=ARROW
state=ACTIVE
file="images/arrow-bg.svg"
stretch=FALSE
overlay_file="images/colorspecific/arrow-up_normal.svg"
overlay_stretch=FALSE
arrow_direction=UP}
image{
function=ARROW
state=ACTIVE
file="images/arrow-bg.svg"
stretch=FALSE
overlay_file="images/colorspecific/arrow-down_normal.svg"
overlay_stretch=FALSE
arrow_direction=DOWN}
image{
function=ARROW
state=ACTIVE
file="images/arrow-bg.svg"
stretch=FALSE
overlay_file="images/colorspecific/arrow-left_normal.svg"
overlay_stretch=FALSE
arrow_direction=LEFT}
image{
function=ARROW
state=ACTIVE
file="images/arrow-bg.svg"
stretch=FALSE
overlay_file="images/colorspecific/arrow-right_normal.svg"
overlay_stretch=FALSE
arrow_direction=RIGHT}
image{
function=ARROW
state=PRELIGHT
file="images/arrow-bg.svg"
stretch=FALSE
overlay_file="images/colorspecific/arrow-up_normal.svg"
overlay_stretch=FALSE
arrow_direction=UP}
image{
function=ARROW
state=PRELIGHT
file="images/arrow-bg.svg"
stretch=FALSE
overlay_file="images/colorspecific/arrow-down_normal.svg"
overlay_stretch=FALSE
arrow_direction=DOWN}
image{
function=ARROW
state=PRELIGHT
file="images/arrow-bg.svg"
stretch=FALSE
overlay_file="images/colorspecific/arrow-left_normal.svg"
overlay_stretch=FALSE
arrow_direction=LEFT}
image{
function=ARROW
state=PRELIGHT
file="images/arrow-bg.svg"
stretch=FALSE
overlay_file="images/colorspecific/arrow-right_normal.svg"
overlay_stretch=FALSE
arrow_direction=RIGHT}}}
class"GtkScrollbar"style"scrollbar"

style "scrolledwindow"{
xthickness=1
ythickness=1
bg[NORMAL]=shade(0.95,@base_color)
bg[PRELIGHT]=shade(0.95,@base_color)
bg[SELECTED]=shade(0.95,@base_color)
bg[ACTIVE]=shade(0.95,@base_color)
bg[INSENSITIVE]=shade(0.95,@base_color)
engine"mist"{}}
class"GtkScrolledWindow"style"scrolledwindow"

style "scrolledwindow2"{
xthickness=0
ythickness=0
bg[NORMAL]=shade(0.95,@base_color)
bg[PRELIGHT]=shade(0.95,@base_color)
bg[SELECTED]=shade(0.95,@base_color)
bg[ACTIVE]=shade(0.95,@base_color)
bg[INSENSITIVE]=shade(0.95,@base_color)
engine"mist"{}}
widget"*GtkNotebook*GtkScrolledWindow"style"scrolledwindow2"

style "scrolledwindow3"{
xthickness=1
ythickness=1
engine"pixmap"{
image{
function=SHADOW
file="images/scrolledwindow-border.svg"
border={2,2,2,2}
stretch=TRUE}}}
widget"*GtkWindow.GtkTable.GtkScrolledWindow"style"scrolledwindow3"
widget"*GtkWindow.GtkVBox.GtkScrolledWindow"style"scrolledwindow3"

style"scrollbarsteppers"{
GtkScrollbar::has-backward-stepper=0
GtkScrollbar::has-forward-stepper=0
GtkScrollbar::has-secondary-backward-stepper=0
GtkScrollbar::has-secondary-forward-stepper=0
}class"*"style"scrollbarsteppers"
