style"tooltip"{
xthickness=4
ythickness=6
fg[NORMAL]="#ffffff"
fg[PRELIGHT]="#ffffff"
fg[SELECTED]="#ffffff"
fg[ACTIVE]="#ffffff"
fg[INSENSITIVE]="#ffffff"
bg[NORMAL]="#454545"
bg[PRELIGHT]="#000000"
bg[SELECTED]="#000000"
text[NORMAL]="#ffffff"
text[PRELIGHT]="#ffffff"
text[ACTIVE]="#ffffff"
text[SELECTED]="#ffffff"
text[INSENSITIVE]="#ffffff"
engine"mist"{}}
widget"gtk-tooltip*"style"tooltip"
