##use industrial since it is impossible to theme the checkboxes fully with pixmaps!
style"treeview"{
xthickness=0
ythickness=0
engine"industrial"{}}
class"*GtkTreeView*"style"treeview"

style"treeviewheader"{
xthickness=0
ythickness=2
GtkButton::inner-border={4,4,1,4}
bg[NORMAL]=@base_color
bg[SELECTED]=@selected_base_color
bg[PRELIGHT]=@base_color
bg[ACTIVE]=@selected_base_color
bg[INSENSITIVE]=@base_color
engine"pixmap"{
image{
function=BOX
shadow=OUT
file="images/colorspecific/base-bg.svg"
stretch=FALSE
overlay_file="images/header-shadow.svg"
overlay_border={0,1,0,1}
overlay_stretch=TRUE}
image{
function=BOX
shadow=IN
file="images/colorspecific/base-bg.svg"
stretch=FALSE
overlay_file="images/header-shadow_pressed.svg"
overlay_border={0,3,2,1}
overlay_stretch=TRUE}}}
widget_class"*.<GtkTreeView>.<GtkButton>"style"treeviewheader"
widget_class"*.<GtkCTree>.<GtkButton>"style"treeviewheader"
widget_class"*.<GtkList>.<GtkButton>"style"treeviewheader"
widget_class"*.<GtkCList>.<GtkButton>"style"treeviewheader"
